#!/usr/bin/env bash
set -eo pipefail

export PATH=$HOME/.local/bin:$PATH
# Color codes for the terminal presentation
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== STARTING LOCAL DEVSECOPS PIPELINE ===${NC}"

# AI & GitLab Configuration
export OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5-coder:1.5b}"
export GITLAB_URL="${GITLAB_URL:-http://localhost:30080}"
export GITLAB_PROJECT_ID="${GITLAB_PROJECT_ID:-1}"
export GITLAB_TOKEN="${GITLAB_TOKEN:-}"

# Check for required tools
for cmd in curl jq git; do
    if ! command -v $cmd &> /dev/null; then
        echo -e "${RED}Error: $cmd is not installed. Please install it to use AI features.${NC}"
        exit 1
    fi
done

handle_failure_with_ai() {
    local step_name=$1
    local error_log=$2

    echo -e "${BLUE}[AI] Analyzing failure in $step_name...${NC}"
    
    if [ -z "$GITLAB_TOKEN" ]; then
        echo -e "${RED}[AI] GITLAB_TOKEN is not set. Skipping AI fix and MR creation. Here is the log:${NC}"
        echo "$error_log"
        exit 1
    fi

    local app_content=""
    local test_content=""
    [ -f "app.py" ] && app_content=$(cat app.py)
    [ -f "test.py" ] && test_content=$(cat test.py)
    
    local jq_escaped_prompt=$(jq -n --arg app "$app_content" --arg test "$test_content" --arg error "$error_log" '{
        model: env.OLLAMA_MODEL,
        prompt: "A pipeline step failed.\nError log:\n\($error)\n\napp.py:\n\($app)\n\ntest.py:\n\($test)\n\nFix the code. Return ONLY a valid JSON object with two keys: \"filename\" (either \"app.py\" or \"test.py\") and \"content\" (the fully fixed code for that file). Do not include markdown code blocks or any other text.",
        stream: false,
        format: "json"
    }')

    echo -e "${BLUE}[AI] Asking Ollama ($OLLAMA_MODEL) for a fix...${NC}"
    
    local ai_response=$(curl -s -X POST http://localhost:11434/api/generate \
        -H "Content-Type: application/json" \
        -d "$jq_escaped_prompt")

    local fixed_json=$(echo "$ai_response" | jq -r '.response')
    local filename=$(echo "$fixed_json" | jq -r '.filename')
    local fixed_code=$(echo "$fixed_json" | jq -r '.content')
    
    if [ "$filename" == "null" ] || [ -z "$filename" ] || [ "$fixed_code" == "null" ]; then
        echo -e "${RED}[AI] Failed to parse a valid JSON fix from Ollama.${NC}"
        echo "Raw response: $fixed_json"
        exit 1
    fi

    local branch_name="ai-fix-${step_name}-$(date +%s)"
    
    echo -e "${GREEN}[AI] Fix generated for $filename. Creating branch $branch_name...${NC}"
    
    git checkout -b "$branch_name"
    echo "$fixed_code" > "$filename"
    git add "$filename"
    git commit -m "AI automated fix for $step_name in $filename"
    
    echo -e "${BLUE}[AI] Pushing to GitLab...${NC}"
    git push origin "$branch_name"

    echo -e "${BLUE}[AI] Opening Merge Request...${NC}"
    local mr_payload=$(jq -n --arg branch "$branch_name" --arg title "AI automated fix for $step_name" '{
        source_branch: $branch,
        target_branch: "main",
        title: $title,
        description: "This is an automated fix generated by Ollama."
    }')

    curl -s -X POST "${GITLAB_URL}/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests" \
         -H "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
         -H "Content-Type: application/json" \
         -d "$mr_payload" > /dev/null

    echo -e "${GREEN}[AI] Merge Request successfully opened! Review it on GitLab.${NC}"
    exit 1
}

# Check docker permissions
if ! docker info >/dev/null 2>&1; then
    echo -e "${RED}Docker access denied. Attempting to fix permissions (sudo may ask for password)...${NC}"
    sudo chmod 666 /var/run/docker.sock || { echo -e "${RED}Failed to fix Docker permissions!${NC}"; exit 1; }
fi

step_1_lint() {
    echo -e "\n[1/7] Ruff Linting and formatting check..."
    local output
    if ! output=$(ruff check . --fix 2>&1); then
        echo -e "${RED}Linting failed!${NC}"
        handle_failure_with_ai "lint" "$output"
    fi
}

step_2_test() {
    echo -e "\n[2/7] Running unit tests (Pytest)..."
    local output
    if ! output=$(python3 test.py 2>&1); then
        echo -e "${RED}Test failed! Pipeline stopped.${NC}"
        handle_failure_with_ai "test" "$output"
    fi
}

step_3_dependency_scan() {
    echo -e "\n[3/7] Scanning third-party dependencies (Snyk)..."
    snyk test --file=requirements.txt || echo -e "${RED}Snyk identification missing, step skipped (simulation mode).${NC}"
}

step_4_secret_scan() {
    echo -e "\n[4/7] Scanning for hardcoded secrets (Gitleaks)..."
    gitleaks detect --source=. -v --no-git || { echo -e "${RED}Critical error: Hardcoded secret found!${NC}"; exit 1; }
}

step_5_build() {
    echo -e "\n[5/7] Building Docker Image (Multi-stage build)..."
    docker build -t local-app:latest .
}

step_6_image_scan() {
    echo -e "\n[6/7] Scanning the built Docker Image (Trivy)..."
    trivy image --severity HIGH,CRITICAL local-app:latest || { echo -e "${RED}Security check rejected the image!${NC}"; exit 1; }
}

step_7_kubernetes_deploy() {
    echo -e "\n[7/7] Preparing local Kubernetes (Kind) cluster..."
    
    # 1. If an old cluster is already running, delete it for a clean slate
    if kind get clusters | grep -q "local-pipeline-cluster"; then
        echo "Cleaning up old cluster..."
        kind delete cluster --name local-pipeline-cluster
    fi

    # 2. Creating a new cluster
    kind create cluster --name local-pipeline-cluster

    echo -e "\n[7/7.b] Loading the secure Docker Image into the K8s cluster..."
    # This is the key step: pushing the locally Trivy-checked image into K8s without a registry
    kind load docker-image local-app:latest --name local-pipeline-cluster

    echo -e "\n[7/7.c] Deploying the application using the deployment manifest..."
    kubectl apply -f k8s/deployment.yml

    echo "Waiting for Pods to start (Kubernetes Orchestration)..."
    # Replacing manual check, waiting for all Pods to be "Ready"
    kubectl rollout status deployment/local-app-deployment --timeout=60s

    echo -e "\n[7/7.d] Starting local port-forward for testing..."
    # Running port-forward in the background to access from browser
    kubectl port-forward svc/local-app-service 8080:8080 &
    PID_FORWARD=$!
    
    sleep 3
    echo "Final health check through the K8s Service..."
    curl -f http://localhost:8080/health || { 
        echo -e "${RED}The Kubernetes deployment started, but the app is not responding!${NC}"; 
        kill $PID_FORWARD; 
        exit 1; 
    }

    # Stopping the background port-forward at the end of the script
    kill $PID_FORWARD
}

# Running in order
step_1_lint
step_2_test
step_3_dependency_scan
step_4_secret_scan
step_5_build
step_6_image_scan
step_7_kubernetes_deploy

echo -e "\n${GREEN}=== SUCCESS: THE LOCAL PIPELINE HAS PASSED ALL GATES ===${NC}"